export const REQUEST_RESET = 'REQUEST_RESET';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const CLEAR_OTP_REQUEST  ='CLEAR_OTP_REQUEST';
export const CLEAR_OTP_SUCCESS  ='CLEAR_OTP_SUCCESS';