
export const GET_NERBY_DOCTOR_REQUEST = 'GET_NERBY_DOCTOR_REQUEST';
export const GET_NERBY_DOCTOR_SUCCESS = 'GET_NERBY_DOCTOR_SUCCESS';
export const GET_NERBY_DOCTOR_FAILURE = 'GET_NERBY_DOCTOR_FAILURE';
