export const GET_SPECIALLIST_REQUEST = 'GET_SPECIALLIST_REQUEST';
export const GET_SPECIALLIST_SUCCESS = 'GET_SPECIALLIST_SUCCESS';
export const GET_SPECIALLIST_FAILURE = 'GET_SPECIALLIST_FAILURE';


