export const GET_FEVORITE_TRAINER_REQUEST = 'GET_FEVORITE_TRAINER_REQUEST';
export const GET_FEVORITE_TRAINER_SUCCESS = 'GET_FEVORITE_TRAINER_SUCCESS';
export const GET_FEVORITE_TRAINER_FAILURE = 'GET_FEVORITE_TRAINER_FAILURE';
