export const GET_QUESTIONARY_REQUEST = 'GET_QUESTIONARY_REQUEST';
export const GET_QUESTIONARY_SUCCESS = 'GET_QUESTIONARY_SUCCESS';
export const GET_QUESTIONARY_FAILURE = 'GET_QUESTIONARY_FAILURE';


