
export const GET_NERBY_TRAINER_REQUEST = 'GET_NERBY_TRAINER_REQUEST';
export const GET_NERBY_TRAINER_SUCCESS = 'GET_NERBY_TRAINER_SUCCESS';
export const GET_NERBY_TRAINER_FAILURE = 'GET_NERBY_TRAINER_FAILURE';
export const GET_TRAINER_SESSION_REQUEST ="GET_TRAINER_SESSION_REQUEST"
