export const ADD_FEVORITE_TRAINER_REQUEST = 'ADD_FEVORITE_TRAINER_REQUEST';
export const ADD_FEVORITE_TRAINER_SUCCESS = 'ADD_FEVORITE_TRAINER_SUCCESS';
export const ADD_FEVORITE_TRAINER_FAILURE = 'ADD_FEVORITE_TRAINER_FAILURE';
export const REMOVE_FEVORITE_TRAINER_REQUEST = 'REMOVE_FEVORITE_TRAINER_REQUEST';
export const REMOVE_FEVORITE_TRAINER_SUCCESS = 'REMOVE_FEVORITE_TRAINER_SUCCESS';
export const REMOVE_FEVORITE_TRAINER_FAILURE = 'REMOVE_FEVORITE_TRAINER_FAILURE';
