// Import Image
const Images={
    address_Home: require('_images/address_Home.png'),
    star2: require('_images/star2.png'),
    doctorImg:require('_images/doctorImg.jpg'),
    listone: require('_images/listone.png'),
    formaladdress: require('_images/formaladdress.png'),
    fees: require('_images/fees.png'),
    education: require('_images/education.png'),
    calender2:require('_images/calender2.png'),
    googleIcon: require('_images/google.png'),
    sidebar:require('_images/sidebarbg.png'),
    fbIcon: require('_images/facebook.png'),
    promocodebg:require('_images/promocodebg.png'),
    appleicon: require('_images/apple.png'),
    selectnumber:require('_images/selectnumber.png'),
    selectnumber:require('_images/selectnumber.png'),
    Cardiologist:require('_images/Cardiologist.png'),
    searchhome:require('_images/searchhome.png'),
    feicon:require('_images/4eicon.png'),
    loginBGMain:require('_images/loginbg.png'),
    back :require('_images/back.png'),
    next :require('_images/next.png'),
    mailLight :require('_images/mail.png'),
    logo :require('_images/logo.png'),
    logowhite:require('_images/logowhite.png'),
    lock :require('_images/lock.png'),
    nameIcon:require('_images/userprofile2.png'),
    menuMore:require('_images/Menu-more.png'),
    address2:require('_images/address2.png'),
    addressprofile:require('_images/pickuplocation.png'),

    upload:require('_images/upload.png'),
    downArrow:require('_images/down-arrow.png'),
    tick:require('_images/tick.png'),
    thankyou:require('_images/thankyou.png'),
    hamburger:require('_images/toggle-bar.png'),
    hamburgerBlack:require('_images/toggle-bar-black.png'),
    hometick:require('_images/hometick.png'),
    online:require('_images/online.png'),
    offline:require('_images/offline.png'),
    clock:require('_images/clock.png'),
    gail:require('_images/gail.png'),
    dummyuser:require('_images/dummyuser.png'),
    addtrainer:require('_images/addtrainer.png'),
    homeprofile:require('_images/home.png'),
    invitefriend:require('_images/invitefriend.png'),
    myappointments:require('_images/My-Appointment.png'),
    support:require('_images/helpsupport.png'),
    promotion:require('_images/promotion.png'),
    socail:require('_images/socail.png'),
    wallet:require('_images/wallet.png'),
    dispute:require('_images/Dispute.png'),
    earning:require('_images/earning.png'),
    manageservice:require('_images/manageservice.png'),
    calender:require('_images/calender.png'),
    address2:require('_images/address2.png'),
    address1:require('_images/Address.png'),
    delete:require('_images/delete.png'),
    add:require('_images/plus.png'),
    editProfile:require('_images/editProfile.png'),
    profilebg:require('_images/profilebg.png'),
    logout:require('_images/logout.png'),
    adduser:require('_images/adduser.png'),
    price:require('_images/price.png'),
    additional:require('_images/additional.png'),
    backwhite:require('_images/backwhite.png'),
    listtick:require('_images/listtick.png'),
    list:require('_images/list.png'),
    wallet2:require('_images/wallet2.png'),
    homeicon:require('_images/homeicon.png'),
    cart:require('_images/cart.png'),
    more:require('_images/more.png'),
    moreactive:require('_images/moreactive.png'),
    cartactive:require('_images/cartactive.png'),
    listactive:require('_images/listactive.png'),
    wallet2:require('_images/wallet2.png'),
    contact:require('_images/contact.png'),
    emailgreen:require('_images/emailgreen.png'),
    phonegreen:require('_images/phonegreen.png'),
    refer:require('_images/refer.png'),
    bank:require('_images/bank.png'),
    edit:require('_images/edit.png'),
    payment:require('_images/payment.png'),
    gym:require('_images/gym.png'),
    homebg:require('_images/homebg.png'),
    userround:require('_images/userround.png'),
    personaltrainer:require('_images/personaltrainer.png'),
    arrowgreen:require('_images/arrowgreen.png'),
    arrowblue:require('_images/arrowblue.png'),
    heartround:require('_images/heartround.png'),
    star:require('_images/star.png'),
    nearby:require('_images/nearby.png'),
    invite:require('_images/invite.png'),
    twitter:require('_images/twittericon.png'),
    instagram:require('_images/instaicon.png'),
    facebook:require('_images/fbicon.png'),
    visa:require('_images/Visa.png'),
    addcard:require('_images/payment.png'),
    card:require('_images/card.png'),
    mastercard:require('_images/mastercard.png'),
    unchecked:require('_images/uncheaked.png'),
    checked:require('_images/checked.png'),
    info:require('_images/info.png'),
    chat:require('_images/videocalgreenl.png'),
    videocall:require('_images/videocall.png'),
    call:require('_images/call.png'),

    listround:require('_images/listround.png'),
    camera:require('_images/camera.png'),
    tickblack:require('_images/tickblack.png'),
    starunfilled:require('_images/starunfilled.png'),
    stargray:require('_images/stargray.png'),
    notfound:require('_images/notfound.png'),
    notfound2:require('_images/notfound2.jpg'),
    radio:require('_images/radio.png'),
    cash:require('_images/cash.png'),
    radioactive:require('_images/radioactive.png'),
    locationgym:require('_images/locationgym.png'),
    helpandsupport:require('_images/helpandsupport.png')
}
module.exports=Images;