export const GET_FEVORITE_GYMS_REQUEST = 'GET_FEVORITE_GYMS_REQUEST';
export const GET_FEVORITE_GYMS_SUCCESS = 'GET_FEVORITE_GYMS_SUCCESS';
export const GET_FEVORITE_GYMS_FAILURE = 'GET_FEVORITE_GYMS_FAILURE';
