export const MOBILE_REQUESTED = 'MOBILE_REQUESTED';
export const LOGIN_WITH_SOCIAL_REQUEST = 'LOGIN_WITH_SOCIAL_REQUEST';
export const MOBILE_SUCCESS = 'MOBILE_SUCCESS';
export const LOGIN_WITH_SOCIAL_SUCCESS = 'LOGIN_WITH_SOCIAL_SUCCESS';
export const MOBILE_FAIL = 'MOBILE_FAIL';

export const BASIC_SETTING_SUCCESS = 'BASIC_SETTING_SUCCESS'
export const BASIC_SETTING_FAIL = 'BASIC_SETTING_FAIL'
export const BASIC_SETTING_REQUEST = "BASIC_SETTING_REQUEST"