export const ADD_FEVORITE_GYMS_REQUEST = 'ADD_FEVORITE_GYMS_REQUEST';
export const ADD_FEVORITE_GYMS_SUCCESS = 'ADD_FEVORITE_GYMS_SUCCESS';
export const ADD_FEVORITE_GYMS_FAILURE = 'ADD_FEVORITE_GYMS_FAILURE';
export const REMOVE_FEVORITE_GYMS_REQUEST = 'REMOVE_FEVORITE_GYMS_REQUEST';
export const REMOVE_FEVORITE_GYMS_SUCCESS = 'REMOVE_FEVORITE_GYMS_SUCCESS';
export const REMOVE_FEVORITE_GYMS_FAILURE = 'REMOVE_FEVORITE_GYMS_FAILURE';
